### PR TITLE
Enhancement: Implement LowerFirst rule

### PR DESCRIPTION
**Pull request by localheinz**
This PR
- [x] implements a `LowerFirst` rule

### CODE REVIEW

**Comment by rick-nu** [comment]
Thank you for your PR @localheinz!

I'm trying to think of use cases for the lower-first filter-rule. The only think I can come up with is `CamelCase` to `camelHump`, but that might be used more then I might expect. I will give this some more thought to decide if we want to offer this as a default filter-rule. I will leave this PR open for now. Please let me know if you know some more use-cases or think that the one above will most likely be used a lot :smile:

**Comment by localheinz** [comment]
@RickvdStaaij 

To be honest, I only added it so we have a match for `Lower`, as we've got `Upper` and a matching `UpperFirst` rule.

**Comment by rick-nu** [comment]
Ah alright then, I will close this one for now. Thank you for your honesty :wink: If it turns out that this is requested again in the future, I'll reopen this :smile:

**Comment by localheinz** [comment]
@RickvdStaaij 

:+1:

**Pull request closed without merging**
