### PR TITLE
Slug new chars

### PR DESCRIPTION
**Pull request by jhuet**
### What?

Other characters needed to be slugged : ( ) = | ~

### Checklist

- [x] Added unit test for added/fixed code
- [ ] Updated the documentation
- [ ] Scrutinizer code coverage is 100%
- [ ] Scrutinizer code quality is as high as possible

### CODE REVIEW

**Comment by rick-nu** [comment]
Hey @jhuet, thank you for your PR!

This makes me think though, why don't we use a `[^\w\d]+` regex? That will replace everything that's not a number or a letter.

**Comment by jhuet** [comment]
Yes, alright, that sounds like a better approach @RickvdStaaij :)

**Comment by jhuet** [comment]
Hey @RickvdStaaij, what do you think about merging and tagging this change ? Thanks !

**Comment by rick-nu** [comment]
@jhuet whoops! Sorry! Thanks man! Lets gooooo!

**Comment by rick-nu** [comment]
Released in `v1.5.1`, thanks again!

**Pull request merged**
